#!/bin/bash

if [ ! -e "$JAVA_HOME" ]; then
    echo "The JAVA_HOME environment variable is not set to a valid Java distribution."
    exit 1
fi

echo -n "Cleaning the build to ensure a fresh build ... "
./gradlew --console=plain clean > /dev/null 2>&1
echo done

tmpfile=$(mktemp -dt "$(basename $0).XXXXXXXXXX")

echo -n "Building robot code ... "
./gradlew --console=plain build > $tmpfile/out 2>&1

if [ $? -ne 0 ]; then
    echo FAILED
    echo
    echo
    cat $tmpfile/out
    echo
    echo
    echo ==========================================================================
    echo "The build of the robot code failed, therefore the simulation tests were skipped."
    echo "Please fix the build errors and run this script again"
    rm -rf $tmpfile
    exit 1
fi

echo build complete and all unit tests passed.
echo
echo


runtests

